<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://www.thesis-management-system-v2.example.com"
    nsPrefix="tms.example.v2.root">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesis" lowerBound="1"
        eType="#//Thesis" eOpposite="#//Thesis/students"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeachingStaffMember" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="examinedTheses" upperBound="-1"
        eType="#//Thesis" eOpposite="#//Thesis/examiners"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervisedTheses" upperBound="-1"
        eType="#//Thesis" eOpposite="#//Thesis/supervisors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" lowerBound="1"
        eType="#//Department" eOpposite="#//Department/teachingStaff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thesis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" lowerBound="1"
        upperBound="-1" eType="#//Student" eOpposite="#//Student/thesis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervisors" lowerBound="1"
        upperBound="-1" eType="#//TeachingStaffMember" eOpposite="#//TeachingStaffMember/supervisedTheses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examiners" lowerBound="1"
        upperBound="-1" eType="#//TeachingStaffMember" eOpposite="#//TeachingStaffMember/examinedTheses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teachingStaff" lowerBound="1"
        upperBound="-1" eType="#//TeachingStaffMember" eOpposite="#//TeachingStaffMember/department"/>
  </eClassifiers>
</ecore:EPackage>
